version: '3.8'

services:
  db:
    image: postgres:15
    container_name: jobtracker_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: apatel
      POSTGRES_DB: jobtrackr
    volumes:
      - ./backend/db-init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  

  backend:
    build: ./backend
    container_name: jobtracker_backend
    depends_on: 
      - db
    environment: 
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: apatel
      DB_NAME: jobtrackr
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: jobtracker_frontend
    depends_on: 
      - backend
    ports:
      - "3000:80"
    environment:
      - IS_DOCKER=true

volumes: 
  pgdata:
